import re

isocitrate = "MKTRTQQIEELQKEWTQPRWEGITRPYSAEDVVKLRGSVNPECTLAQLGAAKMWRLLHGE\
              SKKGYINSLGALTGGQALQQAKAGIEAVYLSGWQVAADANLAASMYPDQSLYPANSVPAV\
              VERINNTFRRADQIQWSAGIEPGDPRYVDYFLPIVADAEAGFGGVLNAFELMKAMIEAGA\
                AAVHFEDQLASVKKCGHMGGKVLVPTQEAIQKLVAARLAADVTGVPTLLVARTDADAADL\
                ITSDCDPYDSEFITGERTSEGFFRTHAGIEQAISRGLAYAPYADLVWCETSTPDLELARR\
                FAQAIHAKYPGKLLAYNCSPSFNWQKNLDDKTIASFQQQLSDMGYKFQFITLAGIHSMWF\
                NMFDLANAYAQGEGMKHYVEKVQQPEFAAAKDGYTFVSHQQEVGTGYFDKVTTIIQGGTS\
                SVTALTGSTEESQF"

regex = "K[KR]CGH[LMQR]"

FASTA_ID = "P28240"
PROSITE_ID = "PS00161"


match = re.search(regex, isocitrate)
start = match.start()
site = match.group(0)

print('Isocitrate lyase (FASTA_ID = {})  contains its active site (PROSITE_ID = {}) '
      'starting from {}th position: {}'.format(FASTA_ID, PROSITE_ID, start, site))
